# Generated by Django 2.2.7 on 2019-11-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(default='123456789', max_length=20)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('Tel', models.CharField(max_length=10, null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('FName', models.CharField(max_length=20, null=True)),
                ('LName', models.CharField(max_length=20, null=True)),
                ('StartWork', models.DateField(null=True)),
                ('Salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(default='123456789', max_length=20)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('Tel', models.CharField(max_length=10, null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('FName', models.CharField(max_length=20, null=True)),
                ('LName', models.CharField(max_length=20, null=True)),
                ('Reliable', models.IntegerField(default=10)),
            ],
        ),
    ]
