# Generated by Django 2.2.7 on 2019-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbn',
            name='Name',
        ),
        migrations.AddField(
            model_name='book',
            name='Name',
            field=models.CharField(default='defaultName', max_length=20),
        ),
    ]
