# Generated by Django 2.2.7 on 2019-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('A', 'Available'), ('R', 'Rented')], default='A', max_length=1)),
                ('Category', models.CharField(choices=[('FIC', 'Fiction'), ('BUS', 'Business'), ('SC', 'Science'), ('N/A', 'None')], default='N/A', max_length=3)),
                ('Author', models.CharField(max_length=40)),
                ('ISBN', models.CharField(max_length=13)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('GadgetID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('A', 'Available'), ('N', 'NotAvailable')], default='A', max_length=1)),
                ('PurchasedDate', models.DateField()),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Capacity', models.IntegerField()),
                ('Type', models.CharField(choices=[('M', 'MeetingRoom'), ('S', 'SleepingRoom')], default='M', max_length=1)),
                ('Status', models.CharField(choices=[('A', 'Available'), ('N', 'NotAvailable')], default='A', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='penalty',
            name='PenaltyID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Penalty_Time',
            fields=[
                ('Date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('Date', 'Time')},
            },
        ),
        migrations.CreateModel(
            name='Book_Time',
            fields=[
                ('StartDate', models.DateField(primary_key=True, serialize=False)),
                ('EndDate', models.DateField()),
                ('RenewTimes', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('StartDate', 'EndDate')},
            },
        ),
    ]
