# Generated by Django 2.2.7 on 2019-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191114_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='Address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='FName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='LName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='Salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='StartWork',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='Tel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='FName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='LName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Tel',
            field=models.CharField(max_length=10),
        ),
    ]
