# Generated by Django 2.2.7 on 2019-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191115_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Reliable',
        ),
    ]
