# Generated by Django 2.2.7 on 2019-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_reliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
